name: This is a Sample Actions
on: [push]
jobs:
  Action1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16
      - name: Install node_modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Step finish
        run: echo "Hurray !!!"