name: This is a Sample Actions
on: [push]
jobs:
  Action1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16
      - run: tree
      - run: node -v 